<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="3.8.0" />
    <PackageReference Include="Selenium.WebDriver" Version="4.34.0" />
    <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="4.34.0" />
    <PackageReference Include="Stubble.Core" Version="1.10.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
